function R = radius(in1)
%RADIUS
%    R = RADIUS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    19-Oct-2020 19:24:36

x1 = in1(:,1);
x2 = in1(:,3);
y1 = in1(:,2);
y2 = in1(:,4);
t2 = periodic_x(x1-x2,y1-y2,0);
t3 = periodic_y(x1-x2,y1-y2,0);
t5 = periodic_x(x1-x2,y1-y2,1);
t7 = periodic_y(x1-x2,y1-y2,1);
t8 = periodic_x(x1-x2,y1-y2,2);
t9 = periodic_y(x1-x2,y1-y2,2);
t10 = periodic_x(x1-x2,y1-y2,3);
t11 = periodic_y(x1-x2,y1-y2,3);
t12 = periodic_x(x1-x2,y1-y2,4);
t13 = periodic_y(x1-x2,y1-y2,4);
R = [sqrt(t2^2+t3^2)*0.5,sqrt(t5^2+t7^2)*0.5,sqrt(t8^2+t9^2)*0.5,sqrt(t10^2+t11^2)*0.5,sqrt(t12^2+t13^2)*0.5];
