function R = radius(in1)
%RADIUS
%    R = RADIUS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    28-Oct-2020 14:28:17

x1 = in1(:,1);
x2 = in1(:,3);
y1 = in1(:,2);
y2 = in1(:,4);
v = periodic_xy(x1-x2,y1-y2,0);
t2 = v(1);
t3 = v(2);
v = periodic_xy(x1-x2,y1-y2,1);
t5 = v(1);
t7 = v(2);
v = periodic_xy(x1-x2,y1-y2,2);
t8 = v(1);
t9 = v(2);
v = periodic_xy(x1-x2,y1-y2,3);
t10 = v(1);
t11 = v(2);
v = periodic_xy(x1-x2,y1-y2,4);
t12 = v(1);
t13 = v(2);
v = periodic_xy(x1-x2,y1-y2,5);
t14 = v(1);
t15 = v(2);
v = periodic_xy(x1-x2,y1-y2,6);
t16 = v(1);
t17 = v(2);
R = [sqrt(t2^2+t3^2)*0.5,sqrt(t5^2+t7^2)*0.5,sqrt(t8^2+t9^2)*0.5,sqrt(t10^2+t11^2)*0.5,sqrt(t12^2+t13^2)*0.5,sqrt(t14^2+t15^2)*0.5,sqrt(t16^2+t17^2)*0.5];
